/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.pages.DataPassword;
import org.example.pages.MainPage;
// import org.example.pages.components.*;
// import org.example.pages.components.Input;
// import org.example.pages.components.Label;
// import org.example.pages.components.SelectInput;
// import org.example.pages.components.Space;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        DataPassword.loadCSVData();
        new MainPage("Aplikasi Store Password", 100).draw();
        DataPassword.saveCSVData();

    }
}
